#!/bin/bash

saycfg default;

KEYS="`gsettings get org.gnome.settings-daemon.plugins.media-keys custom-keybindings | sed 's/]//g'`";
NEWKEY="'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/say/'";

if [ ${#KEYS} -le 5 ]; then
	ADD="[$NEWKEY]";
else
	ADD="[$KEYS, $NEWKEY]";
fi

gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "$ADD"

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/say/ name 'Say!'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/say/ command 'say xsel'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/say/ binding '<Super>Escape'
